app:
  baseUrl: '${RHDH_BASE_URL}'
backend:
  baseUrl: '${RHDH_BASE_URL}'
  cors:
    origin: '${RHDH_BASE_URL}'
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
    img-src:
      - "'self'"
      - 'data:'

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  session:
    secret: '${SESSION_SECRET}'
catalog:
  import:
    entityFilename: catalog-info.yaml
    # pullRequestBranchName: rhdh-integration
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [API, Component, User, Group, Location, Resource, System, Template]
  locations:
    - type: url
      target: https://github.com/redhat-developer/rhdh/blob/main/catalog-entities/all.yaml
    - type: url
      target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates.yaml
    - type: file
      target: ./catalog-entities/users.yaml
    - type: file
      target: ./catalog-entities/components.yaml
    - type: file
      target: ./catalog-entities/operators.yaml
    - type: file
      target: ./catalog-entities/resources.yaml
    - type: file
      target: ./catalog-entities/plugins.yaml
