# NOTE: This global dynamic plugins configuration will be overridden by config/dynamic-plugins.yaml
# To add any plugin configuration, please add it to the dynamic-plugins.yaml file instead
# global:
#   dynamic:
#     includes:
#       - 'dynamic-plugins.default.yaml'
#     plugins: []
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml
    extraEnvVarsSecrets:
      - rhdh-secrets
    extraEnvVars: # need to look to see if these are required or not ...
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        value: '0'
      - name: SEGMENT_TEST_MODE
        value: 'true'
      - name: BACKEND_SECRET
        valueFrom:
          secretKeyRef:
            key: backend-secret
            name: '{{ include "rhdh.backend-secret-name" $ }}'
      - name: POSTGRESQL_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: postgres-password
            name: '{{- include "rhdh.postgresql.secretName" . }}'
    extraVolumeMounts:
      - name: dynamic-plugins-root
        mountPath: /opt/app-root/src/dynamic-plugins-root
      - name: extensions-catalog
        mountPath: /extensions
      - name: temp
        mountPath: /tmp
      - name: rbac-policy
        mountPath: /opt/app-root/src/rbac
      - name: catalog-entities
        mountPath: /opt/app-root/src/catalog-entities
    extraVolumes:
      # -- Ephemeral volume that will contain the dynamic plugins installed by the initContainer below at start.
      - name: dynamic-plugins-root
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  # -- Size of the volume that will contain the dynamic plugins. It should be large enough to contain all the plugins.
                  storage: 5Gi
      # Volume that will expose the `dynamic-plugins.yaml` file from the `dynamic-plugins` config map.
      # The `dynamic-plugins` config map is created by the helm chart from the content of the `global.dynamic` field.
      - name: dynamic-plugins
        configMap:
          defaultMode: 420
          name: dynamic-plugins
          optional: true
      # Optional volume that allows exposing the `.npmrc` file (through a `dynamic-plugins-npmrc` secret)
      # to be used when running `npm pack` during the dynamic plugins installation by the initContainer.
      - name: dynamic-plugins-npmrc
        secret:
          defaultMode: 420
          optional: true
          secretName: '{{ printf "%s-dynamic-plugins-npmrc" .Release.Name }}'
      # Optional volume that allows adding a container registry `auth.json` file (through a `dynamic-plugins-registry-auth` secret)
      # to be used when installing plugins from secure container registries during the dynamic plugins installation by the initContainer.
      - name: dynamic-plugins-registry-auth
        secret:
          defaultMode: 416
          optional: true
          secretName: '{{ printf "%s-dynamic-plugins-registry-auth" .Release.Name }}'
      - name: npmcacache
        emptyDir: {}
      # -- Ephemeral volume used by the install-dynamic-plugins init container to extract catalog entities from the catalog index image.
      # Mounted at the /extensions path in the backstage-backend main container for automatic discovery by the extension catalog backend providers.
      - name: extensions-catalog
        emptyDir: {}
      - name: temp
        emptyDir: {}
      - name: rbac-policy
        configMap:
          defaultMode: 420
          name: rbac-policy
      - name: catalog-entities
        projected:
          sources:
            - configMap:
                name: users-config-map
            - configMap:
                name: operators-config-map
            - configMap:
                name: plugins-config-map
            - configMap:
                name: components-config-map
            - configMap:
                name: resources-config-map
