apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      envs:
        - name: RHDH_BASE_URL
          value: "${RHDH_BASE_URL}"
        - name: CATALOG_INDEX_IMAGE
          value: "quay.io/rhdh/plugin-catalog-index:${CATALOG_INDEX_TAG}"
      secrets:
        - name: rhdh-secrets
  database:
    enableLocalDb: true
